### PR TITLE
Update Android SDK to api level 28.

### PR DESCRIPTION
**Pull request by senpo**
Use the latest version of Android SDK and build tools.

### CODE REVIEW

**Comment by senpo** [comment]
I just signed the cla!

**Comment by Kernald** [comment]
It would be nice to have a way to customise it, rather than having a hard-coded version here.

**Comment by ronshapiro** [comment]
Migrating to the approach in https://github.com/google/dagger/issues/1276#issuecomment-485497982 is probably the best option (and most configurable). That would be a SUPER valuable contribution if you wanted to take it on. It's medium-sized, though.

**Comment by Kernald** [comment]
Oh, Indeed. I'll try to find some time to change that this week-end.

**Pull request closed without merging**
